// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gps-tracker/HistoryScreen.tsx": () => import("../components/mockups/gps-tracker/HistoryScreen.tsx"),
  "./components/mockups/gps-tracker/HomeScreen.tsx": () => import("../components/mockups/gps-tracker/HomeScreen.tsx"),
  "./components/mockups/gps-tracker/RecordingScreen.tsx": () => import("../components/mockups/gps-tracker/RecordingScreen.tsx")
};
